---
name: Bundle-Bricolage
version: 1.9.0
author:
  - David Wheeler <david@kineticode.com>
abstract: Modules required to run Bricolage content management system.
license: perl
provides:
  Bundle::Bricolage:
    file: lib/Bundle/Bricolage.pm
    version: 1.9.0
generated_by: Module::Build version 0.2702
