--- #YAML:1.0
name: Bundle-Bricolage
version: 1.8.0
license: perl
distribution_type: module
requires: {}
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Bundle::Bricolage:
    file: lib/Bundle/Bricolage.pm
    version: 1.8.0
generated_by: Module::Build version 0.21
