--- #YAML:1.0
name: Bundle-Bricolage
version: 1.8.0
author:
  - David Wheeler <david@wheeler.net>
abstract: |-
  Modules required to run Bricolage content management system.
license: perl
provides:
  Bundle::Bricolage:
    file: lib/Bundle/Bricolage.pm
    version: 1.8.0
generated_by: Module::Build version 0.25
